"""initial assessment schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assessments',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_subject_id'), 'assessments', ['subject_id'], unique=False)
    op.create_table('students',
    sa.Column('roll_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_no')
    )
    op.create_table('documents',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('index_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'kind', 'sha256')
    )
    op.create_index(op.f('ix_documents_assessment_id'), 'documents', ['assessment_id'], unique=False)
    op.create_table('questions',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('qid', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'qid')
    )
    op.create_index(op.f('ix_questions_assessment_id'), 'questions', ['assessment_id'], unique=False)
    op.create_table('submissions',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', 'file_sha256')
    )
    op.create_index(op.f('ix_submissions_assessment_id'), 'submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('ai_total', sa.Float(), nullable=False),
    sa.Column('final_total', sa.Float(), nullable=True),
    sa.Column('max_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('subquestions',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('full_id', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'key')
    )
    op.create_index('ix_subq_full', 'subquestions', ['full_id'], unique=False)
    op.create_index(op.f('ix_subquestions_question_id'), 'subquestions', ['question_id'], unique=False)
    op.create_table('model_answers',
    sa.Column('subquestion_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subquestion_id')
    )
    op.create_table('rubrics',
    sa.Column('subquestion_id', sa.Uuid(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subquestion_id')
    )
    op.create_table('student_responses',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('subquestion_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('mapping_confidence', sa.Float(), nullable=False),
    sa.Column('region_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extraction_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'subquestion_id')
    )
    op.create_index(op.f('ix_student_responses_submission_id'), 'student_responses', ['submission_id'], unique=False)
    op.create_index(op.f('ix_student_responses_subquestion_id'), 'student_responses', ['subquestion_id'], unique=False)
    op.create_table('evaluation_plans',
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('response_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['student_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_plans_response_id'), 'evaluation_plans', ['response_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('ai_marks', sa.Float(), nullable=False),
    sa.Column('final_marks', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['student_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_response_id'), 'human_reviews', ['response_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('expected_concepts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('partial_credit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'code')
    )
    op.create_index(op.f('ix_rubric_criteria_rubric_id'), 'rubric_criteria', ['rubric_id'], unique=False)
    op.create_table('evaluation_tasks',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('evaluator', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('input_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['evaluation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_tasks_plan_id'), 'evaluation_tasks', ['plan_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('raw_output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('retrieval_status', sa.String(length=30), nullable=False),
    sa.Column('retrieved_chunks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['student_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['evaluation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_response_id'), 'evaluation_results', ['response_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_task_id'), 'evaluation_results', ['task_id'], unique=False)
    op.create_table('evidence',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('region_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_id'], ['evaluation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_result_id'), 'evidence', ['result_id'], unique=False)
    op.create_table('criterion_scores',
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('awarded', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['student_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'criterion_id')
    )
    op.create_index(op.f('ix_criterion_scores_response_id'), 'criterion_scores', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_criterion_scores_response_id'), table_name='criterion_scores')
    op.drop_table('criterion_scores')
    op.drop_index(op.f('ix_evidence_result_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_evaluation_results_task_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_response_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_evaluation_tasks_plan_id'), table_name='evaluation_tasks')
    op.drop_table('evaluation_tasks')
    op.drop_index(op.f('ix_rubric_criteria_rubric_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_human_reviews_response_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_evaluation_plans_response_id'), table_name='evaluation_plans')
    op.drop_table('evaluation_plans')
    op.drop_index(op.f('ix_student_responses_subquestion_id'), table_name='student_responses')
    op.drop_index(op.f('ix_student_responses_submission_id'), table_name='student_responses')
    op.drop_table('student_responses')
    op.drop_table('rubrics')
    op.drop_table('model_answers')
    op.drop_index(op.f('ix_subquestions_question_id'), table_name='subquestions')
    op.drop_index('ix_subq_full', table_name='subquestions')
    op.drop_table('subquestions')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assessment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_questions_assessment_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_documents_assessment_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('students')
    op.drop_index(op.f('ix_assessments_subject_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
